name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}

    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o .
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Install CycloneDX CLI tool
      run: dotnet tool install CycloneDX 
    - name: Run CycloneDX 
      run: dotnet CycloneDX MyAwesomePDFGenerator.csproj -f bom.json -j
    - name: Generate hashes
      shell: bash
      id: hash
      run: |
        # sha256sum generates sha256 hash for all artifacts.
        # base64 -w0 encodes to base64 and outputs on a single line.
        echo "::set-output name=hashes::$(sha256sum MyAwesomePDFGenerator.1.0.0.nupkg bom.json| base64 -w0)"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
          path: | 
              MyAwesomePDFGenerator.1.0.0.nupkg
              bom.json
          name: MyAwesomePDFGenerator
          if-no-files-found: error
          retention-days: 5
  
  provenance:
    needs: [build]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@main
    with:
      base64-subjects: "${{ needs.build.outputs.hashes }}"
      compile-generator: true
