name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output ./pack
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: CycloneDX .NET Generate SBOM
      # You may pin to the exact commit or the version.
      # uses: CycloneDX/gh-dotnet-generate-sbom@c183e4ac30e5b99354cb9a98c38548e07c538346
      uses: CycloneDX/gh-dotnet-generate-sbom@v1.0.1
      with:
        # The path to a .sln, .csproj, .vbproj, or packages.config file or the path to a directory which will be recursively analyzed for packages.config files
        path: MyAwesomePDFGenerator.csproj
        # Output directory
        out: ./pack
        # Produce a JSON BOM instead of XML, set to any value instead of false
        json: true
    - name: cosign-installer
      # You may pin to the exact commit or the version.
      # uses: sigstore/cosign-installer@ced07f21fb1da67979f539bbc6304c16c0677e76
      uses: sigstore/cosign-installer@v2.7.0
    - name: Sign the package
      env: 
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign-blob package/MyAwesomePDFGenerator.1.0.0.nupkg
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          name: Output
          path: pack/*.nupkg
          if-no-files-found: error
          retention-days: 5
